# -*- coding: utf-8 -*-
"""PythonBasics.ipynb

Automatically generated by Colaboratory.

## ***System Version***
"""

import sys
print(sys.version)

"""### Basics"""

print("Hi!")                        # 1st prog.

a=10
b=10.1
print("a")
print(a)
print(type(a))
print(type(b))
print(b)
print(sys.getsizeof(a))
print(sys.getsizeof(b))

"""Variable & Types"""

# Commented out IPython magic to ensure Python compatibility.
a=5
b="Champs"
c=[1,2,4]
d=5.2
# %whos
del d
print("\n")
# %whos

"""Multi-line Comments"""

'''a=8
b=6'''
a=5

print(b)

"""Arithmetic Operators"""

b=a
a=10
print("a+b: ",a+b)
print("a-b: ",a-b)
print("a/b: ",a/b)
print("a%b: ",a%b)
print("a*b: ",a*b)
print("a//b: ",a//b)       # floor function
print("a^b: ",a**b)        # same as pow(a,b) - power

"""Boolean"""

a=False
b=True
print(type(a))
print(type(a))
print((a and b)!=(a or b))

"""Getting I/O from User"""

name=input("Enter your name: ")
dob=input("Enter your Date of Birth: ")
height=float(input("Enter your height: "))
print("Name: {0}, YearofBirth: {1}, Height: {2} ft.".format(name,dob,height))

"""For loop"""

for i in range(5):
  print(i)

"""### List"""

numList=[]
for i in range(1,10):
  print(i)
  numList.append(i*3)
print("\n")
print(numList)

strList={"Name":"Ankan","YOB":1994,"Weight":51}
for i in strList:
  print(i,strList[i])

"""### Functions"""

def display():
  print("Hello Everyone")
display()

def arith(a,b):
  sum=a+b
  diff=a-b
  div=a/b
  print("ADD: {0},SUB: {1},DIV: {2}".format(sum,diff,div))

var1=int(input("Enter 1st number: "))
var2=int(input("Enter 2nd number: "))
arith(var1,var2)

def arith(a,b):
  sum=a+b
  diff=a-b
  div=a/b
  return sum,diff,div
var1=int(input("Enter 1st number: "))
var2=int(input("Enter 2nd number: "))
result=arith(var1,var2)
print(result)
print("Difference= ",result[1])

def add(*data):
  sum=0
  for i in range(len(data)):
    sum=sum+data[i]
  return sum
a=1
b=2
c=3
print("Total: ",add(a,b,c))

def info(**data):
  for i in data:
    print("Variable Name is: ",i)
    print("Variable Value is: ",data[i])
info(x="Ankan",b=24)

def typeCheck(value):
  if isinstance(value,str):
    print("It is string")
  else:
    print("It is number")
var="5"                          # same for '5' or 'some_name'
typeCheck(var)

"""### String"""

data="Hello Champs"

print(len(data))        # length of data
print(data[2])          # letter by its index
print(data[:6])         # until index
print(data[3:])         # from index
print(data[1:11])       # from & to index
print(data[::-1])       # reverse by index

data2=" Hello,Champs "
strippedData=data2.strip()                  # remove spaces at begining and end
print(strippedData)
cleanData=strippedData.split(",")           # split data based on delimitter
print(cleanData)
print(cleanData[1])
print(cleanData[1].upper())                 # change into uppercase
print(cleanData[1].lower())                 # change into lowercase
print(cleanData[1].capitalize())            # change into propercase
print(strippedData.replace(",","**"))       # replacing